### PR TITLE
Updating time format in all templates

### PR DESCRIPTION
**Pull request by preetriti1**

### CODE REVIEW

**Comment by derek1ee** [comment]
+ @Parth ***@***.***>
________________________________

**Review by joechung2008 — APPROVED** [review]

**Comment by joechung2008** [comment]
Let's add Parth to future pull requests for his review.

**Comment by preetriti1** [comment]
This should not have been merged before Friday :(

**Comment by shahparth-lab** [comment]
I had an offline chat with @***@***.***> and will be more careful - will make sure to only approve/submit feedback rather - sorry :(

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
